version: '3.3'

services: 
    postgresql:
        image: 'postgres:12.4'
        ports: 
         - '5432:5432'
        environment: 
         - POSTGRES_PASSWORD=Password1234
        volumes: 
         - data-volume-pgsql:/var/lib/postgresql/data
    pgadmin:
        image: 'dpage/pgadmin4'
        ports: 
         - '8080:80'
        environment: 
         - PGADMIN_DEFAULT_EMAIL=admin@example.com
         - PGADMIN_DEFAULT_PASSWORD=Password1234
volumes: 
    data-volume-pgsql: