version: '3.3'

services: 
    sqlserver:
        image: 'mcr.microsoft.com/mssql/server:2019-latest'
        ports: 
         - '1433:1433'
        environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=Password1234
        volumes: 
         - data-volume-mssql:/var/opt/mssql
volumes: 
    data-volume-mssql: